#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/fonts.sh"  # Loads all defined fonts

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# sketchybar --bar position=top height=24 blur_radius=30 color=$BAR_COLOR # Extend Monitor
sketchybar --bar position=top height=43 blur_radius=30 color=$BAR_COLOR # MacOS Monitor (Display more space)

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items
# icon.font="Hack Nerd Font:Bold:15.0"
# label.font="Hack Nerd Font:Bold:12.0"
default=(
    padding_left=5
    padding_right=5
    icon.font="SF Pro:Semibold:10.0"
    label.font="SF Pro:Semibold:12.0"
    background.color=$ITEM_BG_COLOR
    background.corner_radius=3
    # background.height=14 # Extend Monitor
    background.height=24 # MacOS Monitor (Display more space)
    icon.color=$WHITE
    label.color=$WHITE
    icon.padding_left=4
    icon.padding_right=4
    label.padding_left=10
    label.padding_right=10
)
sketchybar --default "${default[@]}"

# Left side items
# source $ITEM_DIR/spaces.sh
source $ITEM_DIR/aerospace.sh
source $ITEM_DIR/front_app.sh

# Right side items
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/aerospace_mode.sh
source $ITEM_DIR/media.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
